resolver: lts-8.11
packages:
- '.'
- location:
    git: https://github.com/cpdurham/huvc.git
    commit: c840f79a35c75d9ab8c26359a4927fdf83a78b50
  extra-dep: true
extra-deps:
- 'accelerate-1.0.0.0'
- 'accelerate-io-1.0.0.0'
- 'accelerate-llvm-1.0.0.0'
- 'accelerate-llvm-ptx-1.0.0.0'
- 'chaselev-deque-0.5.0.5'
- 'colour-accelerate-0.1.0.0'
- 'cuda-0.7.5.3'
- 'llvm-hs-4.0.1.0'
extra-package-dbs: []
